### PR TITLE
Added translation support, Polish language translation and fixed some bugs with UI

### PR DESCRIPTION
**Pull request by PawelPleskaczynski**
Hello,
in this pull request I added support for translations for Stellarium-web. It's easy to add and manage translations, everything is in a single file. I also added Polish translation, most of the UI elements are translated, as well as every object type and galaxy type. Of course, I didn't forget about Wikipedia articles in Polish language. You don't have to choose a language from any menu, language is detected automatically. If there's no translation available for a language, Stellarium-web's language is set to English.
Here's what happens when my browser is set to Polish language:
screenshot_20190112_202918
screenshot_20190112_203022
screenshot_20190112_203030
screenshot_20190112_203048
Here's the same menu, but with my browser's language set to English:
screenshot_20190112_203107

By the way, should I:
 - ~add a new menu entry in settings for changing language?~ I added it anyways
 - translate privacy policy and data credits?

~The first point isn't really necessary in my opinion and~ I'm not sure about the second point, I don't know if a not-adult outsider can translate legal documents.

I also fixed an issue with selected object info box and with search list. Sometimes there were too many things to display and no scrollbar was shown, now there's a scrollbar in a situation like this.

Here's a video of these changes:

[YouTube video](https://youtu.be/SeTSVihay6E)

### CODE REVIEW

**Comment by timdream** [comment]
@PawelPleskaczynski @xalioth May I know what's the status of this pull request? I have a [ten-year-old promotion page](https://timc.idv.tw/stellarium/) promoting Stellarium in Taiwan, and I am happy to redirect that to Stellarium Web once the site is localized. I don't think it make sense for me to keep offer outdated software there!

**Comment by gzotti** [comment]
@timdream, the desktop version of Stellarium is by no means outdated, but there are 4 releases per year. Stellarium (desktop) and Stellarium Web have different pros and cons. It would make sense if your site gets updated from promoting ten year old versions, though.

The desktop version has been translated into many languages, so probably your old translation packages are no longer required, but if translations are still missing, you may join our translation team at Transifex.

See https://stellarium.org/zh_TW/ for our current community-translated homepage.

**Comment by timdream** [comment]
@gzotti Thanks for the input! I know Stellarium desktop is still being updated, it's just that I don't have the means (specifically, non-VM Windows with OpenGL) to validate its localization support anymore. With that I am keen to promote the Web version instead. So... are we going to see this pull request being merged soon?

**Comment by gzotti** [comment]
@timdream Stellarium for desktop works on Windows, Linux (even on many ARM boards) and Mac. Just not Chromebooks. 
I am only involved in the desktop development, cannot comment on the review/merge of this PR.

**Comment by xalioth** [comment]
Hi Thimothy,

sorry for being very unreactive. The actual web version has somewhat
diverged with the code in github so I was not able to apply your patch.

I have been having difficulties separating the code containing sensitive
data (backend DB stuff with passwords and private service keys) and the
rest of the un-sensitive GUI so I didn't pushed the last GUI updates on
github (most of the code is in the engine, which is of course available in
the Stellarium Web Engine sub-project). That's the reason I didn't merge
your pull request yet.

I need to find a way to clearly separate the backend/DB code from the
frontend code in 2 separated git projects.. I started this task a few
months ago but it was harder than I thought (because of docker and
deployment issues), so I gave up temporarily. I'm not forgetting this task
but I have currently other priorities (I need to work on the Mobile version
until I can actually pay myself with that..)

Fabien

**Comment by PawelPleskaczynski** [comment]
@xalioth that's ok, do you think it'll be possible to merge this PR after you push your UI changes here?


PS it's mine PR

**Comment by xalioth** [comment]
Hi Pawel,

yes I know you're the original author of the PR thanks!!Tthe change will
require a rebase, and I'll need to do a proper code review, but yes it's on
my TODO list.

Fabien

**Comment by PawelPleskaczynski** [comment]
That's cool, thank you for the reply!

**Comment by timdream** [comment]
@xalioth Thanks for the response. I am a fan of your work! I totally understand your priorities — managing open source project and life balance can be hard.

Just to close the loop here — I ended up scrub my old content and ask people to visit stellarium.org there should people stump on that in search. I am more than happy to promote Stellarium Web there too once it receives localization support.

**Comment by timdream** [comment]
@PawelPleskaczynski Thank you for working on this too.

**Comment by PawelPleskaczynski** [comment]
I tried to run the website, I built the engine using `make js` command, but after copying both `stellarium-web-engine.js` and `.wasm` to the `assets/js` folder, I'm getting this error in the latest Firefox version:
```
./src/assets/sw_helpers.js
35:16-29 "export 'default' (imported as 'StelWebEngine') was not found in '@/assets/js/stellarium-web-engine.js'
 @ ./src/assets/sw_helpers.js
 @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/App.vue
 @ ./src/App.vue
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://0.0.0.0:8080 webpack/hot/dev-server babel-polyfill ./src/main.js ./src/assets/js/stellarium-web-engine.js
```
Do you know what might be the issue? :thinking:

**Comment by xalioth** [comment]
Hi Pawel,

you need to build the make gen-es6 for using in the web version.

However, the (new) workflow to run the dev version is now, from a clean checkout of the stellarium-web-engine project, stellarium-web branch
make setup
cd web-frontend
make setup
make dev

The engine will be build by this last command, and the web GUI will be run by a local node server, running inside a docker container.

Please note that I will suppress this repo soon, as it is now superseded by the stellarium-web-engine one.

Fabien

**Comment by PawelPleskaczynski** [comment]
Hi Fabien,
Thank you for the instructions! Now I won't have to do everything manually.

I added translations to both UI in frontend and object types in the C engine, I'll do a PR tomorrow after I clean up everything :smiley:

**Comment by xalioth** [comment]
OK! I had a look at the old PR, and I would really prefer a solution where
the english string remains as "clear text" in the code. It makes the code
more readable, and also it's probably better for SEO.
For example, there is something like
https://github.com/Polyconseil/vue-gettext which could be quite appropriate.

Also, for the object types from the engine (the otypes), we already have
some (incomplete) translations for some languages (in gettext .po files)
that we will contribute in the repo, no need to spend time on that!

Thanks!
Fabien

**Comment by PawelPleskaczynski** [comment]
That's a cool library, I'll take a look at it

**Pull request closed without merging**
